name: "Task"
about: "Create a new actionable task for the team."
title: "[Task] "
labels: ["Type: Task"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### Task Overview

  - type: input
    id: summary
    attributes:
      label: Description
      description: A brief summary of what this task involves and how it contributes to the project (e.g., feature, bug fix, improvement).
      placeholder: "e.g., Implement password reset functionality"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 📋 Checklist

  - type: checkboxes
    id: checklist
    attributes:
      label: Task Checklist
      description: Use this to track progress.
      options:
        - label: Understand the task / clarify doubts
        - label: Define requirements & scope
        - label: Assign collaborator(s)
        - label: Code / Build / Implement
        - label: Peer review & feedback
        - label: Test functionality
        - label: Update documentation (if needed)
        - label: Final check & mark complete

  - type: markdown
    attributes:
      value: |
        ### 📁 Resources / Dependencies

  - type: textarea
    id: resources
    attributes:
      label: Resources or Blocking Tasks
      description: Mention linked issues, PRs, design documents, or external resources.
      placeholder: "e.g., Related issues: #12, #34. Mockup: [Figma link]"

